### ISSUE TITLE
[BUG REPORT] Vitastats single agent

### ISSUE THREAD

**Issue by BhuvanDasari** [Project-DC/pygeneses#79]
**Describe the bug**
Not showing vita stats for specified data set. 

**To Reproduce**
1. Just load data set into vita stats

**Expected behavior**
A window appears saying 'Please wait  Generating Graphs' .But doesn't load at all

**Screenshots**
![image](https://user-images.githubusercontent.com/70709385/92137459-c5a23300-ee2a-11ea-9cd8-be299c92549d.png)

**Desktop (please complete the following information):**
 - OS: Windows

File Name:
Players_Data_initial_population\Players_Data_initial_population_5 
It is available in slack playerdata channel

**Comment by frankhart2018** [comment]
Fixed in v0.1.7
